"""Interactive (and ``--yes``) setup wizard for qvd-mcp.

The wizard writes ``config.toml``, merges a ``qvd`` entry into the Claude
Desktop config, and runs one initial conversion pass. It is reused from the
``qvd-mcp setup`` CLI command (Wave 3 wires that in).

Design notes:

- Module-level imports of ``qvd_mcp.config`` and ``qvd_mcp.claude_config``
  (not their individual functions) so that monkeypatching
  ``qvd_mcp.config.default_config_path`` / ``qvd_mcp.config.default_log_dir``
  / ``qvd_mcp.claude_config.default_config_path`` in tests is honored at
  call time.
- Single-quoted TOML literal strings for path values — no backslash
  escaping needed on Windows. Paths containing ``'`` are a rare edge case
  and are rejected with a clear error rather than silently mangled.
- ``run_setup`` validates the source directory **before** touching any
  files, so a bad invocation never leaves a half-written config.
- Atomic write for ``config.toml`` via ``.tmp`` + ``os.replace`` to match
  the pattern used elsewhere in the codebase.
"""
from __future__ import annotations

import contextlib
import dataclasses
import logging
import os
import tomllib
from dataclasses import dataclass
from pathlib import Path

from rich.console import Console
from rich.prompt import Confirm, Prompt
from rich.table import Table

from qvd_mcp import claude_config, convert
from qvd_mcp import config as qmcp_config

log = logging.getLogger(__name__)

_QVD_SERVER_COMMAND = "uvx"
_QVD_SERVER_ARGS: list[str] = ["qvd-mcp", "serve"]


class SetupError(Exception):
    """Raised when setup cannot proceed (e.g. missing source directory)."""


@dataclass(frozen=True)
class SetupChoices:
    source_dir: Path
    cache_dir: Path
    patch_claude: bool


def gather_interactive() -> SetupChoices:
    """Prompt the user for source dir, cache dir, and the Claude Desktop opt-in.

    Validates that the source directory exists after each prompt and loops
    until the user provides a valid one (or aborts with Ctrl-C).
    """
    console = Console()
    console.print("[bold]Welcome to qvd-mcp setup.[/bold]\n")

    default_source = Path.home() / "Documents" / "QVDs"
    default_cache = qmcp_config.default_cache_dir()

    while True:
        source_raw = Prompt.ask(
            "1. Where are your QVD files?",
            default=str(default_source),
        )
        source_dir = Path(source_raw).expanduser().resolve()
        if source_dir.is_dir():
            break
        console.print(
            f"[yellow]'{source_dir}' does not exist or is not a directory. "
            "Please try again.[/yellow]"
        )

    cache_raw = Prompt.ask(
        "2. Where should qvd-mcp keep the Parquet cache?",
        default=str(default_cache),
    )
    cache_dir = Path(cache_raw).expanduser().resolve()

    patch_claude = Confirm.ask(
        "3. Add qvd-mcp to your Claude Desktop config?",
        default=True,
    )

    return SetupChoices(
        source_dir=source_dir,
        cache_dir=cache_dir,
        patch_claude=patch_claude,
    )


def _toml_literal_string(value: str) -> str:
    """Return ``value`` quoted as a TOML literal string (``'...'``).

    Literal strings are raw — no escapes are interpreted — which is ideal
    for paths on Windows (``C:\\Users\\...``). The only character that
    cannot appear inside a literal string is the single quote itself;
    callers providing such a path get a clear error rather than a silently
    corrupted config.
    """
    if "'" in value:
        raise SetupError(
            f"path contains a single-quote character, which TOML literal "
            f"strings cannot represent: {value!r}"
        )
    return f"'{value}'"


def write_config_toml(choices: SetupChoices, *, path: Path | None = None) -> Path:
    """Write a minimal ``config.toml`` reflecting ``choices``.

    Uses single-quoted TOML literal strings so backslashes in Windows paths
    are not interpreted as escape sequences. Parent directories are created
    as needed. Writes atomically via ``.tmp`` + ``os.replace`` so a crash
    mid-write can't truncate the file. Returns the final path.
    """
    target = path if path is not None else qmcp_config.default_config_path()
    target.parent.mkdir(parents=True, exist_ok=True)

    source_str = str(choices.source_dir)
    cache_str = str(choices.cache_dir)
    payload = (
        "# qvd-mcp config - generated by `qvd-mcp setup`\n"
        f"source_dir = {_toml_literal_string(source_str)}\n"
        f"cache_dir = {_toml_literal_string(cache_str)}\n"
    )

    tmp = target.with_suffix(target.suffix + ".tmp")
    try:
        tmp.write_text(payload, encoding="utf-8")
        os.replace(tmp, target)
    except OSError:
        # Best-effort cleanup so we don't litter ``.tmp`` files on failure.
        with contextlib.suppress(OSError):
            tmp.unlink()
        raise

    return target


def detect_local_checkout(start: Path | None = None) -> Path | None:
    """Return the qvd-mcp source-repo root if we're running from one.

    Walks up from ``start`` (default: the current working directory) looking
    for a ``pyproject.toml`` whose ``[project].name`` is ``qvd-mcp``. Returns
    ``None`` if no such ancestor exists.

    Used by :func:`run_setup` to wire Claude Desktop at the user's local
    ``uv --directory ... run qvd-mcp serve`` command instead of the
    PyPI-flavoured ``uvx qvd-mcp serve`` while the package is still
    pre-release. Once qvd-mcp ships on PyPI this function keeps working —
    end users just won't be inside a checkout, so it returns ``None`` and
    setup picks the production form.
    """
    base = (start if start is not None else Path.cwd()).resolve()
    for candidate in [base, *base.parents]:
        pyproject = candidate / "pyproject.toml"
        if not pyproject.is_file():
            continue
        try:
            data = tomllib.loads(pyproject.read_text(encoding="utf-8"))
        except (OSError, tomllib.TOMLDecodeError):
            return None
        name = data.get("project", {}).get("name")
        if name == "qvd-mcp":
            return candidate
        # Different project's pyproject — stop walking up. Nesting qvd-mcp
        # inside another Python project is unusual enough that guessing
        # would be more surprising than falling back to the PyPI form.
        return None
    return None


def _claude_desktop_command() -> tuple[str, list[str]]:
    """Pick the command to wire into Claude Desktop for this environment.

    Prefers a detected local checkout (so unreleased versions work
    end-to-end); falls back to the production ``uvx qvd-mcp serve`` form.
    """
    checkout = detect_local_checkout()
    if checkout is not None:
        log.info(
            "local-dev checkout detected at %s; using `uv --directory` form",
            checkout,
        )
        return "uv", ["--directory", str(checkout), "run", "qvd-mcp", "serve"]
    return _QVD_SERVER_COMMAND, list(_QVD_SERVER_ARGS)


def _print_report_table(
    report: convert.ConvertReport, console: Console
) -> None:
    """Render a ConvertReport as a Rich table (same shape as ``cli.convert``)."""
    table = Table(title="Conversion report", title_style="bold")
    table.add_column("Outcome", style="cyan")
    table.add_column("Count", justify="right")
    table.add_row("converted", str(len(report.converted)))
    table.add_row("skipped", str(len(report.skipped)))
    table.add_row("failed", str(len(report.failed)))
    table.add_row("pruned", str(len(report.pruned)))
    console.print(table)


def run_setup(
    *,
    source: Path | None = None,
    cache: Path | None = None,
    no_claude: bool = False,
    yes: bool = False,
) -> None:
    """Drive the whole setup flow.

    In ``yes=True`` mode, ``source`` is required and must be an existing
    directory; ``cache`` defaults to :func:`qvd_mcp.config.default_cache_dir`,
    and ``patch_claude`` is ``True`` unless ``no_claude`` is set.

    In interactive mode, prompts the user for every choice and then honors
    ``no_claude`` as a post-prompt override (so a user who types "yes" to
    the prompt but passed ``--no-claude`` still gets the CLI flag to win).
    """
    console = Console()

    if yes:
        if source is None:
            raise SetupError(
                "--yes mode requires --source to be given explicitly."
            )
        source_resolved = Path(source).expanduser().resolve()
        if not source_resolved.is_dir():
            raise SetupError(
                f"source directory does not exist or is not a directory: "
                f"{source_resolved}"
            )
        cache_resolved = (
            Path(cache).expanduser().resolve()
            if cache is not None
            else qmcp_config.default_cache_dir()
        )
        choices = SetupChoices(
            source_dir=source_resolved,
            cache_dir=cache_resolved,
            patch_claude=not no_claude,
        )
    else:
        choices = gather_interactive()
        if no_claude:
            choices = dataclasses.replace(choices, patch_claude=False)

    config_path = write_config_toml(choices)
    console.print(f"Wrote config to [bold]{config_path}[/bold]")

    if choices.patch_claude:
        claude_path = claude_config.default_config_path()
        # Clean up any legacy entry from before the canonical rename. No-op
        # on fresh installs.
        claude_config.unmerge(claude_config.LEGACY_SERVER_NAME)
        command, args = _claude_desktop_command()
        claude_config.merge(claude_config.QVD_SERVER_NAME, command, args)
        log.info(
            "merged %s entry into %s (command=%s)",
            claude_config.QVD_SERVER_NAME,
            claude_path,
            command,
        )
        console.print(
            f"Merged Claude Desktop entry into [bold]{claude_path}[/bold] "
            f"(command: [cyan]{command} {' '.join(args)}[/cyan])"
        )

    try:
        cfg = qmcp_config.load(
            source_override=choices.source_dir,
            cache_override=choices.cache_dir,
        )
    except qmcp_config.ConfigError as exc:
        raise SetupError(f"could not load config: {exc}") from exc

    console.print("Running initial conversion pass...")
    report = convert.run_once(cfg)
    _print_report_table(report, console)
    console.print(
        "\n[bold green]Setup complete![/bold green] "
        "Restart Claude Desktop and ask it to list your QVDs."
    )
